import {stages,steps,emptyStudy,day,plan} from './study.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function dashboard(c,state){
  const all=c.topics.map(t=>state.study[t.id]||emptyStudy()),due=all.filter(s=>s.reviewAt&&s.reviewAt<=day()).length,started=all.filter(s=>s.stage!=='pending').length;
  const tasks=plan(c.topics,state.study,state.dailyGoal);
  return `<section class="study-dashboard" aria-labelledby="today-title"><div class="section-heading"><div><div class="eyebrow">ESTUDIAR · RECORDAR · PRACTICAR</div><h2 id="today-title">Mi plan de hoy</h2></div><label>Temas por sesión <select id="daily-goal">${[1,2,3,4,5].map(n=>`<option ${state.dailyGoal===n?'selected':''}>${n}</option>`).join('')}</select></label></div><p>${started} de 34 temas empezados · <strong>${due} repasos pendientes</strong>. El plan prioriza repasos vencidos y prácticas por debajo del 70 % de aciertos; después sigue el orden oficial. Ese porcentaje sirve para ordenar el repaso, no como nota de aprobado.</p><div class="today-tasks">${tasks.length?tasks.map(({topic:t,reason})=>`<a href="#tema/${t.id}" class="today-task"><strong>Tema ${t.id} · ${esc(reason)}</strong><span>${esc(t.officialTitle)}</span><small>${t.videos.length?'Abrir estudio y recursos →':'Estudiar con material oficial · sin vídeo en el catálogo →'}</small></a>`).join(''):'<p>No hay tareas pendientes según tu seguimiento. Puedes adelantar un repaso desde el temario.</p>'}</div><p class="study-help">Ver vídeos es una parte del estudio. Marca por separado la lectura, el recuerdo y la práctica. Tu valoración no certifica que domines el tema.</p></section>`;
}
export function topicStudy(topic,state){
  const s=state.study[topic.id]||emptyStudy(),last=s.attempts.at(-1);
  return `<section class="study-panel" data-study-topic="${topic.id}" aria-labelledby="study-title"><div class="section-heading"><h2 id="study-title">Mi preparación · Tema ${topic.id}</h2><a class="text-link" href="#inicio">Ver mi plan de hoy</a></div><label class="study-field">Estado del tema<select id="study-stage">${Object.entries(stages).map(([v,label])=>`<option value="${v}" ${s.stage===v?'selected':''}>${label}</option>`).join('')}</select></label><fieldset class="study-checks"><legend>Pasos de estudio</legend>${Object.entries(steps).map(([v,label])=>`<label><input type="checkbox" data-study-check="${v}" ${s.checks.includes(v)?'checked':''}> ${label}</label>`).join('')}</fieldset><div class="review-box"><h3>Repaso sin mirar</h3><p>Explica las ideas principales, enumera las reglas que recuerdas y compruébalas después en tu material. Anota abajo los errores.</p><label class="study-field">Próximo repaso<input id="review-date" type="date" value="${s.reviewAt}"></label><p>Después de intentarlo:</p><div class="dialog-actions"><button class="button" data-review="again">Necesito reforzarlo · mañana</button><button class="button" data-review="good">Lo recuerdo · espaciar repaso</button></div><p class="study-help">Intervalos orientativos: 1, 3, 7, 14 y 30 días. Puedes cambiar la fecha. Los avisos se muestran al abrir la app.</p></div><form id="practice-form" class="practice-form"><h3>Registrar una práctica</h3><p>Guarda el resultado de un test que hayas hecho con tus materiales. Porcentaje de aciertos sin aplicar penalización por errores.</p><div class="practice-inputs"><label>Preguntas totales<input name="total" type="number" min="1" max="1000" step="1" required inputmode="numeric"></label><label>Aciertos<input name="correct" type="number" min="0" max="1000" step="1" required inputmode="numeric"></label><button class="button primary" type="submit">Guardar resultado</button></div><p id="practice-message" role="status"></p></form>${last?`<p class="last-practice">Última práctica: <strong>${last.correct}/${last.total} · ${Math.round(100*last.correct/last.total)} %</strong> · ${last.date}</p><details><summary>Mis últimas prácticas (${s.attempts.length})</summary><ul>${s.attempts.slice().reverse().map(a=>`<li>${a.date}: ${a.correct} de ${a.total} aciertos (${Math.round(100*a.correct/a.total)} %)</li>`).join('')}</ul></details>`:''}<label class="study-field">Cuaderno de errores<textarea id="study-errors" maxlength="10000" placeholder="Qué confundí, cuál es la regla correcta y dónde la comprobé…">${esc(s.errors)}</textarea></label><p id="study-save" role="status">Seguimiento guardado en este navegador. Incluido en tu copia de seguridad.</p></section>`;
}
