import assert from 'node:assert/strict';
import {emptyStudy,review,plan,afterDays,validDay} from '../study.js';
import {validateBackup} from '../state.js';
const ids=new Set(['I.1','I.2','II.4']),vids=new Set(['video']);
const old={schemaVersion:1,watched:['video'],favorites:[],notes:{'I.1':'Mi nota'},lastTopic:'I.1'};
const upgraded=validateBackup(old,ids,vids);
assert.deepEqual(upgraded.notes,old.notes);assert.deepEqual(upgraded.watched,['video']);assert.deepEqual(upgraded.study,{});assert.equal(upgraded.dailyGoal,2);
let s=review(emptyStudy(),'good','2026-12-31');assert.equal(s.reviewAt,'2027-01-01');
s=review(s,'good','2027-01-01');assert.equal(s.reviewAt,'2027-01-04');
s=review(s,'again','2027-01-04');assert.equal(s.reviewAt,'2027-01-05');assert.equal(s.interval,0);
assert.equal(afterDays(1,'2028-02-28'),'2028-02-29');assert.equal(validDay('2026-02-30'),false);
const topics=[{id:'I.1'},{id:'I.2'},{id:'II.4'}];
const study={'II.4':{...emptyStudy(),reviewAt:'2026-09-08'},'I.2':{...emptyStudy(),attempts:[{date:'2026-09-08',correct:2,total:10}]}};
assert.deepEqual(plan(topics,study,2,'2026-09-09').map(x=>x.topic.id),['II.4','I.2']);
const full={...upgraded,study,dailyGoal:3};assert.deepEqual(validateBackup(JSON.parse(JSON.stringify(full)),ids,vids),full);
assert.throws(()=>validateBackup({...full,study:{'I.1':{...emptyStudy(),attempts:[{date:'2026-09-09',correct:11,total:10}]}}},ids,vids));
assert.throws(()=>validateBackup({...full,study:{'I.1':{...emptyStudy(),stage:'__proto__'}}},ids,vids));
assert.throws(()=>validateBackup({...full,dailyGoal:10},ids,vids));
console.log('Migration, backups, review dates and priority planning passed.');
